export const languages = [
  { value: 'auto', label: 'Auto' },
  { value: 'plaintext', label: 'Plain Text' },
  { value: '1c', label: '1C' },
  { value: 'abnf', label: 'ABNF' },
  { value: 'accesslog', label: 'Access Log' },
  { value: 'actionscript', label: 'ActionScript' },
  { value: 'ada', label: 'Ada' },
  { value: 'angelscript', label: 'AngelScript' },
  { value: 'apache', label: 'Apache' },
  { value: 'applescript', label: 'AppleScript' },
  { value: 'arcade', label: 'Arcade' },
  { value: 'arduino', label: 'Arduino' },
  { value: 'armasm', label: 'ARM Assembly' },
  { value: 'xml', label: 'XML' },
  { value: 'asciidoc', label: 'AsciiDoc' },
  { value: 'aspectj', label: 'AspectJ' },
  { value: 'autohotkey', label: 'AutoHotkey' },
  { value: 'autoit', label: 'AutoIt' },
  { value: 'avrasm', label: 'AVR Assembly' },
  { value: 'awk', label: 'AWK' },
  { value: 'axapta', label: 'Axapta' },
  { value: 'bash', label: 'Bash' },
  { value: 'basic', label: 'BASIC' },
  { value: 'bnf', label: 'BNF' },
  { value: 'brainfuck', label: 'Brainfuck' },
  { value: 'c', label: 'C' },
  { value: 'cal', label: 'CAL' },
  { value: 'capnproto', label: 'Cap\'n Proto' },
  { value: 'ceylon', label: 'Ceylon' },
  { value: 'clean', label: 'Clean' },
  { value: 'clojure', label: 'Clojure' },
  { value: 'clojure-repl', label: 'Clojure REPL' },
  { value: 'cmake', label: 'CMake' },
  { value: 'coffeescript', label: 'CoffeeScript' },
  { value: 'coq', label: 'Coq' },
  { value: 'cos', label: 'COS' },
  { value: 'cpp', label: 'C++' },
  { value: 'crmsh', label: 'crmsh' },
  { value: 'crystal', label: 'Crystal' },
  { value: 'csharp', label: 'C#' },
  { value: 'csp', label: 'CSP' },
  { value: 'css', label: 'CSS' },
  { value: 'd', label: 'D' },
  { value: 'markdown', label: 'Markdown' },
  { value: 'dart', label: 'Dart' },
  { value: 'delphi', label: 'Delphi' },
  { value: 'diff', label: 'Diff' },
  { value: 'django', label: 'Django' },
  { value: 'dns', label: 'DNS Zone' },
  { value: 'dockerfile', label: 'Dockerfile' },
  { value: 'dos', label: 'DOS' },
  { value: 'dsconfig', label: 'dsconfig' },
  { value: 'dts', label: 'DTS' },
  { value: 'dust', label: 'Dust' },
  { value: 'ebnf', label: 'EBNF' },
  { value: 'elixir', label: 'Elixir' },
  { value: 'elm', label: 'Elm' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'erb', label: 'ERB' },
  { value: 'erlang-repl', label: 'Erlang REPL' },
  { value: 'erlang', label: 'Erlang' },
  { value: 'excel', label: 'Excel' },
  { value: 'fix', label: 'FIX' },
  { value: 'flix', label: 'Flix' },
  { value: 'fortran', label: 'Fortran' },
  { value: 'fsharp', label: 'F#' },
  { value: 'gams', label: 'GAMS' },
  { value: 'gauss', label: 'GAUSS' },
  { value: 'gcode', label: 'G-code' },
  { value: 'gherkin', label: 'Gherkin' },
  { value: 'glsl', label: 'GLSL' },
  { value: 'gml', label: 'GML' },
  { value: 'go', label: 'Go' },
  { value: 'golo', label: 'Golo' },
  { value: 'gradle', label: 'Gradle' },
  { value: 'graphql', label: 'GraphQL' },
  { value: 'groovy', label: 'Groovy' },
  { value: 'haml', label: 'Haml' },
  { value: 'handlebars', label: 'Handlebars' },
  { value: 'haskell', label: 'Haskell' },
  { value: 'haxe', label: 'Haxe' },
  { value: 'hsp', label: 'HSP' },
  { value: 'http', label: 'HTTP' },
  { value: 'hy', label: 'Hy' },
  { value: 'inform7', label: 'Inform 7' },
  { value: 'ini', label: 'INI' },
  { value: 'irpf90', label: 'IRPF90' },
  { value: 'isbl', label: 'ISBL' },
  { value: 'java', label: 'Java' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'jboss-cli', label: 'JBoss CLI' },
  { value: 'json', label: 'JSON' },
  { value: 'julia', label: 'Julia' },
  { value: 'julia-repl', label: 'Julia REPL' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'lasso', label: 'Lasso' },
  { value: 'latex', label: 'LaTeX' },
  { value: 'ldif', label: 'LDIF' },
  { value: 'leaf', label: 'Leaf' },
  { value: 'less', label: 'Less' },
  { value: 'lisp', label: 'Lisp' },
  { value: 'livecodeserver', label: 'LiveCode Server' },
  { value: 'livescript', label: 'LiveScript' },
  { value: 'llvm', label: 'LLVM' },
  { value: 'lsl', label: 'LSL' },
  { value: 'lua', label: 'Lua' },
  { value: 'makefile', label: 'Makefile' },
  { value: 'mathematica', label: 'Mathematica' },
  { value: 'matlab', label: 'MATLAB' },
  { value: 'maxima', label: 'Maxima' },
  { value: 'mel', label: 'MEL' },
  { value: 'mercury', label: 'Mercury' },
  { value: 'mipsasm', label: 'MIPS Assembly' },
  { value: 'mizar', label: 'Mizar' },
  { value: 'perl', label: 'Perl' },
  { value: 'mojolicious', label: 'Mojolicious' },
  { value: 'monkey', label: 'Monkey' },
  { value: 'moonscript', label: 'MoonScript' },
  { value: 'n1ql', label: 'N1QL' },
  { value: 'nestedtext', label: 'NestedText' },
  { value: 'nginx', label: 'Nginx' },
  { value: 'nim', label: 'Nim' },
  { value: 'nix', label: 'Nix' },
  { value: 'node-repl', label: 'Node.js REPL' },
  { value: 'nsis', label: 'NSIS' },
  { value: 'objectivec', label: 'Objective-C' },
  { value: 'ocaml', label: 'OCaml' },
  { value: 'openscad', label: 'OpenSCAD' },
  { value: 'oxygene', label: 'Oxygene' },
  { value: 'parser3', label: 'Parser3' },
  { value: 'pf', label: 'PF' },
  { value: 'pgsql', label: 'PostgreSQL' },
  { value: 'php', label: 'PHP' },
  { value: 'php-template', label: 'PHP Template' },
  { value: 'pony', label: 'Pony' },
  { value: 'powershell', label: 'PowerShell' },
  { value: 'processing', label: 'Processing' },
  { value: 'profile', label: 'Profile' },
  { value: 'prolog', label: 'Prolog' },
  { value: 'properties', label: 'Properties' },
  { value: 'protobuf', label: 'Protocol Buffers' },
  { value: 'puppet', label: 'Puppet' },
  { value: 'purebasic', label: 'PureBasic' },
  { value: 'python', label: 'Python' },
  { value: 'python-repl', label: 'Python REPL' },
  { value: 'q', label: 'Q' },
  { value: 'qml', label: 'QML' },
  { value: 'r', label: 'R' },
  { value: 'reasonml', label: 'ReasonML' },
  { value: 'rib', label: 'RIB' },
  { value: 'roboconf', label: 'Roboconf' },
  { value: 'routeros', label: 'RouterOS' },
  { value: 'rsl', label: 'RSL' },
  { value: 'ruleslanguage', label: 'Rules Language' },
  { value: 'rust', label: 'Rust' },
  { value: 'sas', label: 'SAS' },
  { value: 'scala', label: 'Scala' },
  { value: 'scheme', label: 'Scheme' },
  { value: 'scilab', label: 'Scilab' },
  { value: 'scss', label: 'SCSS' },
  { value: 'shell', label: 'Shell' },
  { value: 'smali', label: 'Smali' },
  { value: 'smalltalk', label: 'Smalltalk' },
  { value: 'sml', label: 'SML' },
  { value: 'sqf', label: 'SQF' },
  { value: 'sql', label: 'SQL' },
  { value: 'stan', label: 'Stan' },
  { value: 'stata', label: 'Stata' },
  { value: 'step21', label: 'STEP Part 21' },
  { value: 'stylus', label: 'Stylus' },
  { value: 'subunit', label: 'SubUnit' },
  { value: 'swift', label: 'Swift' },
  { value: 'taggerscript', label: 'Tagger Script' },
  { value: 'yaml', label: 'YAML' },
  { value: 'tap', label: 'TAP' },
  { value: 'tcl', label: 'Tcl' },
  { value: 'thrift', label: 'Thrift' },
  { value: 'tp', label: 'TP' },
  { value: 'twig', label: 'Twig' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'vala', label: 'Vala' },
  { value: 'vbnet', label: 'VB.NET' },
  { value: 'vbscript', label: 'VBScript' },
  { value: 'vbscript-html', label: 'VBScript in HTML' },
  { value: 'verilog', label: 'Verilog' },
  { value: 'vhdl', label: 'VHDL' },
  { value: 'vim', label: 'Vim Script' },
  { value: 'wasm', label: 'WebAssembly' },
  { value: 'wren', label: 'Wren' },
  { value: 'x86asm', label: 'x86 Assembly' },
  { value: 'xl', label: 'XL' },
  { value: 'xquery', label: 'XQuery' },
  { value: 'zephir', label: 'Zephir' },
];